"""add series/season/episode, rescope watchlist and ratings to content-or-series

Revision ID: 06308b6fc128
Revises: 3cfb3be09a33
Create Date: 2026-07-27 12:10:51.430050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06308b6fc128'
down_revision: Union[str, Sequence[str], None] = '3cfb3be09a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_categories',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'category_id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ratings', sa.Column('series_id', sa.Integer(), nullable=True))
    op.alter_column('ratings', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_rating_profile_content'), 'ratings', type_='unique')
    op.create_index('uq_rating_profile_content', 'ratings', ['profile_id', 'content_id'], unique=True, postgresql_where=sa.text('content_id IS NOT NULL'))
    op.create_index('uq_rating_profile_series', 'ratings', ['profile_id', 'series_id'], unique=True, postgresql_where=sa.text('series_id IS NOT NULL'))
    op.create_foreign_key(None, 'ratings', 'series', ['series_id'], ['id'])
    op.add_column('watchlist', sa.Column('series_id', sa.Integer(), nullable=True))
    op.alter_column('watchlist', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_watchlist_profile_content'), 'watchlist', type_='unique')
    op.create_index('uq_watchlist_profile_content', 'watchlist', ['profile_id', 'content_id'], unique=True, postgresql_where=sa.text('content_id IS NOT NULL'))
    op.create_index('uq_watchlist_profile_series', 'watchlist', ['profile_id', 'series_id'], unique=True, postgresql_where=sa.text('series_id IS NOT NULL'))
    op.create_foreign_key(None, 'watchlist', 'series', ['series_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.drop_index('uq_watchlist_profile_series', table_name='watchlist', postgresql_where=sa.text('series_id IS NOT NULL'))
    op.drop_index('uq_watchlist_profile_content', table_name='watchlist', postgresql_where=sa.text('content_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_watchlist_profile_content'), 'watchlist', ['profile_id', 'content_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('watchlist', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('watchlist', 'series_id')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_index('uq_rating_profile_series', table_name='ratings', postgresql_where=sa.text('series_id IS NOT NULL'))
    op.drop_index('uq_rating_profile_content', table_name='ratings', postgresql_where=sa.text('content_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_rating_profile_content'), 'ratings', ['profile_id', 'content_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ratings', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ratings', 'series_id')
    op.drop_table('episodes')
    op.drop_table('series_categories')
    op.drop_table('seasons')
    op.drop_table('series')
    # ### end Alembic commands ###
