"""add role to users

Revision ID: 2295ca2836d9
Revises: 3d75b59fcf40
Create Date: 2026-07-19 00:23:14.027569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2295ca2836d9'
down_revision: Union[str, Sequence[str], None] = '3d75b59fcf40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.String(),
            nullable=False,
            server_default="viewer",
        ),
    )

    # Remove the temporary default after existing rows are populated.
    op.alter_column(
        "users",
        "role",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
