"""add unique constraint to watch_history

Revision ID: c72b0abe201d
Revises: 2295ca2836d9
Create Date: 2026-07-25 11:44:16.229834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72b0abe201d'
down_revision: Union[str, Sequence[str], None] = '2295ca2836d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_history', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_history', 'duration_seconds')
    # ### end Alembic commands ###
